If your application name is `micronautguide` and it has the following https://micronaut-projects.github.io/micronaut-core/latest/guide/#environments[active environments] `ec2`, `cloud`, and `lambda`. The following configuration prefixes are searched:

* `/config/micronautguide_ec2/`
* `/config/micronautguide_cloud/`
* `/config/micronautguide_lambda/`
* `/config/micronautguide/`
* `/config/application_ec2/`
* `/config/application_cloud/`
* `/config/application_lambda/`
* `/config/application/`

If you set:

[configuration]
----
aws:
    distributed-configuration:
        search-active-environments:false
----

The following prefixes are searched:

* `/config/micronautguide/`
* `/config/application/`

If you set:

[configuration]
----
aws:
    distributed-configuration:
        search-common-application:false
----

The following prefixes are searched:

* `/config/micronautguide_ec2/`
* `/config/micronautguide_cloud/`
* `/config/micronautguide_lambda/`
* `/config/micronautguide/`

By setting both:

If you set:

[configuration]
----
aws:
    distributed-configuration:
        search-active-environments:false
        search-common-application:false
----

Only the following prefix is searched:

* `/config/micronautguide/`

IMPORTANT: Reducing the number of prefixes reduces the application's startup.
