The Micronaut's `aws-alexa` module simplifies development of Alexa Skills with Java, Kotlin or Groovy.

dependency:micronaut-aws-alexa[groupId="io.micronaut.aws"]

To create the sample skill described in
https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html[Amazon Documentation - Develop your first skill] with Micronaut's Alexa you will write the same https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#launchrequest-handler[LaunchRequestHandler], https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#helloworldintent-handler[HelloWorldIntent], https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#helpintent-handler[HelpIntent], https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#cancelandstopintent-handler[CancelandStopHandler], https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#fallbackintent-handler[FallbackIntentHandler], https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-java/develop-your-first-skill.html#sessionendedrequest-handler[SessionEndedRequestHandler] handlers.

You will do just one change, you will annotate those handlers with `javax.inject.Singleton`.

[source, java]
----
import com.amazon.ask.dispatcher.request.handler.HandlerInput;
import com.amazon.ask.dispatcher.request.handler.RequestHandler;
import com.amazon.ask.model.Response;
import com.amazon.ask.request.Predicates;

import javax.inject.Singleton;
import java.util.Optional;

@Singleton // <1>
public class HelloWorldIntentHandler implements RequestHandler {

    @Override
    public boolean canHandle(HandlerInput input) {
        return input.matches(Predicates.intentName("HelloWorldIntent"));
    }

    @Override
    public Optional<Response> handle(HandlerInput input) {
        String speechText = "Hello world";
        return input.getResponseBuilder()
                .withSpeech(speechText)
                .withSimpleCard("HelloWorld", speechText)
                .build();
    }

}
----

<1> The Singleton scope indicates only one instance of the bean should exist in the https://docs.micronaut.io/latest/guide/index.html#beanContext[Micronaut's Bean Context]

Typically, the next step will be to provide an instance of
api:aws.alexa.conf.AlexaSkillConfiguration[]. The easiest way to do that is to configure the skill id via configuration:

```yaml
alexa:
  skills:
    myskill:
      skill-id 'xxxx-yaaa-zz123'
```

Micronaut's alexa module provides by default
api:aws.alexa.builders.StandardSkillBuilderProvider[] which creates an SDK instance using the `Skills.standard` builder. You can provide your own implementation of Micronaut's api:aws.alexa.builders.SkillBuilderProvider[].

For each api:aws.alexa.conf.AlexaSkillConfiguration[] bean,
Micronaut uses the builder provided by [api:aws.alexa.builders.SkillBuilderProvider[] to create for you a bean of type http://ask-sdk-java-javadocs.s3-website-us-west-2.amazonaws.com[AlexaSkill] for you and wires up the beans of the following types:

* `com.amazon.ask.dispatcher.request.handler.RequestHandler`
* `com.amazon.ask.dispatcher.request.interceptor.RequestInterceptor`
* `com.amazon.ask.dispatcher.request.interceptor.ResponseInterceptor`
* `com.amazon.ask.dispatcher.exception.ExceptionHandler`
* `com.amazon.ask.builder.SkillBuilder`
