Regular Micronaut functions created via `mn create-function` can be deployed to Lambda directly. 

[TIP]
.Using the CLI
====
----
$ mn create-function example
----
====

For example, when using `create-function hello` Micronaut 1.1 and above will create a function that looks like:

[source,java]
----
package example;
import io.micronaut.function.executor.FunctionInitializer;
import javax.inject.*;

@Singleton
public class EchoFunction extends FunctionInitializer { // <1>

    @Inject GreetingService greetingService; // <2>

    public Message sayHello(Message msg) { // <3>
        return greetingService.hello(msg);
    }

    public static void main(String...args) throws IOException { // <4>
        EchoFunction function = new EchoFunction();
        function.run(args, (context)-> function.sayHello(context.get(Message.class)));
    }    
}
----

<1> The function shouuld be a simple class annotated with `@Singleton` that extends from `FunctionInitializer` and has no constructor arguments.
<2> You can use dependency injection to inject fields.
<3> The function should be defined as a public method, and accept a single argument that is a simple `java.lang` type or a POJO bean that can be serialized/deserialized to JSON.
<4> You can optionally define a `main` method if you plan to deploy the function to other FaaS environments that use standard in/out if not you can remove the `main` method

The `FunctionInitiazer` super class will bootstrap Micronaut and perform injection on the instance prior to the `echo` method being executed.

An appropriate SAM definition for this function would be:

[source,yaml]
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.EchoFunction::echo

The key part is the `Handler` which should be set to `example.EchoFunction::echo` which is the class name and method name combination. The `main` method is optional and can be removed if it is not needed. The `main` method allows the function to be executed from the cli, for example:

[source,bash]
----
$ echo '{"name":"Fred"}' | java -jar function.jar
----     

The above example pipes the JSON into system in which the functions reads and writes the result to system out. Certain FaaS systems such as OpenFaaS use system in/out for function inputs and outputs, hence with the main method in place you can deploy the function to such systems.

If you need further integration with what AWS Lambda has to offer then this project includes a number of parent classes and utilities to simplify working with the native Lambda APIs.
