plugins {
    id "io.micronaut.build.internal.aws-base"
    id "io.micronaut.build.internal.module"
}
ossIndexAudit {
    excludeCompileOnly = true
}
dependencies {
    testRuntimeOnly(mnTest.junit.platform.launcher)
}
micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.aws:micronaut-aws-common"
    }
}


