plugins {
    id "io.micronaut.build.internal.aws-base"
    id "io.micronaut.build.internal.module"
}
ossIndexAudit {
    excludeCompileOnly = true
}
configurations.all {
    resolutionStrategy {
        force("commons-io:commons-io:2.14.0")
        // first version patched https://ossindex.sonatype.org/component/pkg:maven/commons-io/commons-io
    }
}
dependencies {
    testRuntimeOnly(mnTest.junit.platform.suite)
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation(mnTest.junit.jupiter.api)
}
