repositories {
    mavenLocal {
        content {
            includeGroup("io.micronaut")
        }
    }
    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        name = "Central Portal Snapshots"
        mavenContent {
            snapshotsOnly()
        }
        content {
            includeGroupByRegex("io\\.micronaut(\\..+)?")
        }
    }
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}
