The module `micronaut-aws-xray` introduces HttpServer and HttpClient filters that intercepts the requests and are instrumenting the X-Ray.

== Incoming requests

The HttpServer filter uses provided https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.html[AWSXRayServletFilter]. Read more about provided filter at https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-filters.html[Tracing incoming requests with the X-Ray SDK for Java].

The filter creates new segment that name resolves in this order:

1. Bean of https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/strategy/SegmentNamingStrategy.html[SegmentNamingStrategy] type.
2. https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/strategy/FixedSegmentNamingStrategy.html[FixedSegmentNamingStrategy] configured by `aws.xray.httpfilter.server.fixedSegmentName` property.
3. https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/strategy/FixedSegmentNamingStrategy.html[FixedSegmentNamingStrategy] configured by `micronaut.application.name` property.
4. https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/strategy/FixedSegmentNamingStrategy.html[FixedSegmentNamingStrategy] with default of `code micronaut.xray-http-filter`.

Note that all incoming requests are traced and new https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/entities/Segment.html[Segment] is created.

Finally you can disable tracing of incoming requests by:

.application.yml
[source,yaml]
----
aws:
  xray:
    httpfilter:
      server:
        enabled: false
----

== Outgoing http calls

The HttpClient filter intercepts all outgoing http calls and creates new https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/entities/Subsegment.html[Subsegment]. The subsegment name is derived from the outgoing hostname.

Note you can disable tracing of outgoing http requests by:

.application.yml
[source,yaml]
----
aws:
  xray:
    httpfilter:
      client:
        enabled: false
----