To trace https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-awssdkclients.html[AWS SDK clients outgoing requests] you have to start by adding dependency:

dependency:aws-xray-recorder-sdk-aws-sdk-v2[groupId="com.amazonaws"]

Dependency contains the https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/interceptors/TracingInterceptor.html[TracingInterceptor] that must be configured while building the AWS SDK clients.

Micronaut will automatically configure the https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/interceptors/TracingInterceptor.html[TracingInterceptor] while creation AWS SDK client beans.

Note you can disable AWS SDK beans automatic configuration by:
.application.yml
[source,yaml]
----
aws:
  xray:
    sdkclients:
      enabled: false
----

If you want to automatically instrument *all* AWS SDK clients add depenency:
dependency:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor[groupId="com.amazonaws"]

That depedency causes that *all* AWS SDK clients are automatically instrumented by the `TracingInterceptor` without any additional configuration needed. This approach disadvantage is that you can't control the client's instrumentation with respect to the environment where the application runs.
