AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Example API - example::example
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 320
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ExampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: ExampleApi
