To use the `URLConnection`-based client, you should exclude the other clients from the classpath:

.Maven
[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <exclusions>
        <exclusion>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>apache5-client</artifactId>
        </exclusion>
        <exclusion>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>apache-client</artifactId>
        </exclusion>
        <exclusion>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>netty-nio-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

.Gradle
[source,groovy]
----
implementation "software.amazon.awssdk:s3", {
    exclude group: "software.amazon.awssdk", module: "apache5-client"
    exclude group: "software.amazon.awssdk", module: "apache-client"
    exclude group: "software.amazon.awssdk", module: "netty-nio-client"
}
implementation "software.amazon.awssdk:url-connection-client"
----

Then, you can configure it with the following configuration properties:

include::{includedir}configurationProperties/software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$Builder.adoc[]

The recommended approach is to exclude the other synchronous clients, as shown above. The
`software.amazon.awssdk.http.service.impl` JVM system property can force URLConnection when it is
set to `software.amazon.awssdk.http.urlconnection.UrlConnectionSdkHttpService`. Do not use it as a
way to keep multiple synchronous implementations on the classpath; select a single implementation
instead.

The AWS SDK also recognises the following implementation names:

* `software.amazon.awssdk.http.service.impl`. Possible values:
** `software.amazon.awssdk.http.urlconnection.UrlConnectionSdkHttpService` to force the `URLConnection` based client.
** `software.amazon.awssdk.http.apache5.Apache5SdkHttpService` to use the Apache HttpClient 5.x client (if in the classpath).
** `software.amazon.awssdk.http.apache.ApacheSdkHttpService` to use the legacy Apache HttpClient 4.x client (if in the classpath).
* `software.amazon.awssdk.http.async.service.impl`. Possible values:
** `software.amazon.awssdk.http.nio.netty.NettySdkAsyncHttpService` for the Netty client (if in the classpath).
