An alternative approach to using Micronaut with AWS is to use Micronaut support for the https://github.com/awslabs/aws-serverless-java-container[AWS Serverless Java Container] project.

[TIP]
.Using the CLI with Micronaut 1.1 or above
====
----
$ mn create-app my-app --features aws-api-gateway
----
====

In this arrangement you build your application as a regular REST application, for example:

.Example Controller
[source,java]
----
include::examples/api-gateway-example/src/main/java/example/PingController.java[]
----

You then need to add the `micronaut-function-aws-api-proxy` dependency:

dependency:micronaut-function-aws-api-proxy[groupId="io.micronaut.aws"]

You can then implement a `RequestHandler` that handles the API proxy request:

.Example Stream Lambda Handler
[source,java]
----
include::examples/api-gateway-example/src/main/java/example/StreamLambdaHandler.java[]
----

<1> Micronaut is initialized in the constructor
<2> The API Proxy Request is handled

The api:function.aws.proxy.MicronautLambdaContainerHandler[] class is used to initialization Micronaut and handle the serverless requests.

The `MicronautLambdaContainerHandler` constructor also accepts a `ApplicationContextBuilder` instance which you can use to further customize application bootstrap.

TIP: See the https://github.com/micronaut-projects/micronaut-aws/tree/master/examples/api-gateway-example[Example Application] and associated https://github.com/micronaut-projects/micronaut-aws/blob/master/examples/api-gateway-example/README.md[README] for instructions on how to deploy locally using https://github.com/awslabs/aws-sam-cli[AWS SAM Local] and AWS Cloud Formation for production.

=== `ObjectMapper` configuration

By default, for efficiency reasons, Micronaut uses the default Jackson `ObjectMapper` to communicate with the AWS API proxy.
However, if you have configured it for your application (for example, setting `jackson.propertyNamingStrategy: SNAKE_CASE`)
in a way that it would be incompatible with the API proxy, you can set `aws.proxy.shared-object-mapper: false`, and Micronaut
will create a brand new `ObjectMapper` for the API proxy.

If you wish to further configure this `ObjectMapper`, you can register a `BeanCreatedEventListener<ObjectMapper>` and
filter based on `event.getBeanDefinition()` having an annotation like `@Named("aws")`.