Micronaut AWS provides support for invoking AWS Lambda functions within a Micronaut application context.

To use the features described in this section, you will need to have the `micronaut-function-client-aws` dependency on your classpath:

dependency:micronaut-function-client-aws[groupId="io.micronaut.aws"]

or in alternative the `micronaut-function-client-aws-v2` dependency to use the AWS SDK v2:

dependency:micronaut-function-client-aws-v2[groupId="io.micronaut.aws"]

You can define multiple named functions under the `aws.lambda.functions` configuration.
Each is configured by `AWSInvokeRequestDefinition` that allows setting any property on the underlying `com.amazonaws.services.lambda.model.InvokeRequest` or `software.amazon.awssdk.services.lambda.model.InvokeRequest.Builder` when using v2.

For example, you invoke a function named `AwsLambdaFunctionName`, in the AWS Lambda console, with the following configuration:

[source, yaml]
----
include::test-suite/src/test/resources/application.yml[tags="config"]
----

You create an interface annotated with `@FunctionClient` to invoke the Lambda Function:

snippet::io.micronaut.docs.function.client.aws.atnamed.AnalyticsClient[tags="clazz"]

<1> The value of the `@Named` annotation matches the bean's name used in configuration `aws.lambda.functions.`**analytics**`.function-name`.

Alternatively, you can remove the `@Named` annotation and match the method name to the function bean name.

snippet::io.micronaut.docs.function.client.aws.methodnamed.AnalyticsClient[tags="clazz"]

To configure credentials for invoking the function you can either define a `~/.aws/credentials` file or use `application.yml`. Micronaut registers a api:io.micronaut.aws.sdk.v1.EnvironmentAWSCredentialsProvider[], or api:io.micronaut.aws.sdk.v2.EnvironmentAwsCredentialsProvider[] for v2, that resolves AWS credentials from the Micronaut Environment.

To invoke a function with AWS SDK v1 Micronaut configures a `AWSLambdaAsyncClient` using api:io.micronaut.function.client.aws.AWSLambdaConfiguration[] that allows configuring any of the properties of the `AWSLambdaAsyncClientBuilder` class.

When using v2 instead the service accepts the following configuration properties:

include::{includedir}configurationProperties/io.micronaut.aws.sdk.v2.service.lambda.LambdaConfigurationProperties.adoc[]

Note that the HTTP client, credentials and region will be configured as per described in the <<sdkv2, SDK v2 documentation>>.
