Micronaut AWS provides support for invoking AWS Lambda functions within a Micronaut application context.

To use the features described in this section, you will need to have the `micronaut-function-client-aws` dependency on your classpath.

dependency:micronaut-function-client-aws[groupId="io.micronaut.aws"]

You can define multiple named functions under the `aws.lambda.functions` configuration.
Each is configured by `AWSInvokeRequestDefinition` that allows setting any property on the underlying `com.amazonaws.services.lambda.model.InvokeRequest`.

For example, you invoke a function named `AwsLambdaFunctionName`, in the AWS Lambda console, with the following configuration:

[configuration]
----
include::test-suite/src/test/resources/application.yml[tags="config"]
----

You create an interface annotated with `@FunctionClient` to invoke the Lambda Function:

snippet::io.micronaut.docs.function.client.aws.atnamed.AnalyticsClient[tags="clazz"]

<1> The value of the `@Named` annotation matches the bean's name used in configuration `aws.lambda.functions.`**analytics**`.function-name`.

Alternatively, you can remove the `@Named` annotation and match the method name to the function bean name.

snippet::io.micronaut.docs.function.client.aws.methodnamed.AnalyticsClient[tags="clazz"]

To configure credentials for invoking the function you can either define a `~/.aws/credentials` file or use the application configuration file. Micronaut registers a api:configurations.aws.EnvironmentAWSCredentialsProvider[] that resolves AWS credentials from the Micronaut Environment.

NOTE: To invoke a function Micronaut configures a `AWSLambdaAsyncClient` using api:function.client.aws.AWSLambdaConfiguration[] that allows configuring any of the properties of the `AWSLambdaAsyncClientBuilder` class.
