plugins {
    id "groovy-gradle-plugin"
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation libs.javapoet
    implementation libs.gradle.micronaut
    implementation libs.gradle.kotlin
    implementation("org.sonatype.gradle.plugins:scan-gradle-plugin:2.8.3")
}